# Generated by Django 2.1.5 on 2019-06-26 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Acara', models.CharField(max_length=100)),
                ('Waktu_Mulai', models.DateField()),
                ('Waktu_Selesai', models.DateField()),
                ('Tempat', models.TextField(blank=True, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Acara/')),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Acara',
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('Tanggal', models.DateField(auto_now_add=True)),
                ('Isi', models.TextField(blank=True, null=True)),
                ('Gambar', models.ImageField(blank=True, null=True, upload_to='Berita/')),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Berita',
            },
        ),
        migrations.CreateModel(
            name='FotoAngkatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gambar', models.ImageField(upload_to='Angkatan/')),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Foto Angkatan',
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=50)),
                ('Subjudul', models.CharField(blank=True, max_length=50, null=True)),
                ('Link_to', models.TextField(default='#')),
                ('Slide', models.ImageField(upload_to='homepage/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('Judul_1', models.CharField(default=True, max_length=50)),
                ('Subjudul_1', models.CharField(blank=True, max_length=50, null=True)),
                ('Link_to_1', models.TextField(default='#')),
                ('Slide_1', models.ImageField(default=True, upload_to='homepage/')),
                ('created_1', models.DateTimeField(auto_now=True)),
                ('Judul_2', models.CharField(default=True, max_length=50)),
                ('Subjudul_2', models.CharField(blank=True, max_length=50, null=True)),
                ('Link_to_2', models.TextField(default='#')),
                ('Slide_2', models.ImageField(default=True, upload_to='homepage/')),
                ('created_2', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='NamaAlumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('NIS', models.IntegerField(blank=True, null=True)),
                ('Alamat', models.TextField(blank=True, null=True)),
                ('Akademik', models.CharField(choices=[('Toddler', 'Toddler'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], default=True, max_length=7)),
                ('No_Telp', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Alumni/')),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
        migrations.CreateModel(
            name='RincianAcara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rincian_Acara', models.CharField(max_length=100)),
                ('Waktu_Mulai', models.DateTimeField()),
                ('Waktu_Selesai', models.DateTimeField()),
                ('Foto', models.ImageField(upload_to='Acara/')),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Judul_Acara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Acara')),
            ],
            options={
                'verbose_name_plural': 'Rincian Acara',
            },
        ),
        migrations.CreateModel(
            name='TahunAngkatan',
            fields=[
                ('Angkatan', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('Akademik', models.CharField(choices=[('Toddler', 'Toddler'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=7)),
                ('Keterangan', models.TextField(blank=True, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tahun Angkatan',
            },
        ),
        migrations.AddField(
            model_name='namaalumni',
            name='Angkatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.TahunAngkatan'),
        ),
        migrations.AddField(
            model_name='fotoangkatan',
            name='Angkatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.TahunAngkatan'),
        ),
    ]
