# Generated by Django 2.1.5 on 2019-06-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acara',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=140),
        ),
    ]
