# Generated by Django 2.1.5 on 2019-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_rincianacara_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header_Date', models.DateField()),
                ('Acara', models.ImageField(upload_to='sitesettings/')),
                ('Berita', models.ImageField(upload_to='sitesettings/')),
                ('Rincian_Berita', models.ImageField(upload_to='sitesettings/')),
            ],
            options={
                'verbose_name_plural': 'Header Settings',
            },
        ),
    ]
