# Generated by Django 2.1.5 on 2019-06-27 09:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20190627_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acara',
            name='Keterangan',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
