# Generated by Django 2.1.5 on 2019-06-27 09:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20190627_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acara',
            name='Keterangan',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
