# Generated by Django 2.1.5 on 2019-07-01 12:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_auto_20190627_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rincianacara',
            name='Keterangan',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
