# Generated by Django 2.1.5 on 2019-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_auto_20190701_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='rincianacara',
            name='slug_R',
            field=models.SlugField(default='', editable=False, max_length=140),
        ),
    ]
