# Generated by Django 2.1.5 on 2019-07-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_rincianacara_slug_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rincianacara',
            name='slug_R',
        ),
    ]
